Lesson2/test ping and getbooking
Maxkanzas/ApiTest_Gradle pull request #2
Opened 2024-12-18 17:41 UTC by Maxkanzas

2024-12-18 23:24 UTC, TsakunovR requested changes

2024-12-18 23:24 UTC, TsakunovR commented on src/main/java/core/settings/ApiEndpoints.java
> +    BOOKINGID ("/booking/1");
Некорректно здесь хардкодить id, необходимо удалить
А что если у тебя будет 100 тестов на проверку 100 разных id бронирований. Мы же не будем здесь добавлять все id

2024-12-18 23:24 UTC, TsakunovR commented on src/main/java/core/clients/APIClient.java
> +                .get(ApiEndpoints.BOOKING.getPath())
Здесь не нужно передавать id потому что метод возвращает нам абсолютно все id бронирований которые есть

2024-12-18 23:24 UTC, TsakunovR commented on src/main/java/core/clients/APIClient.java
> +    public Response getBookingId(){
Этот метод должен быть универсальным, чтобы можно было по любому введенному id бронирования получить информацию, если бронирование с таким id существует
Поэтому в этом методе нужно прописать что ожидается параметр

2024-12-18 23:24 UTC, TsakunovR commented on src/main/java/core/clients/APIClient.java
> +                .get(ApiEndpoints.BOOKINGID.getPath())
Соответственно полученный параметр использовать в адресе запроса

2024-12-19 10:36 UTC, Maxkanzas commented on src/main/java/core/settings/ApiEndpoints.java
> +    BOOKINGID ("/booking/1");
А как тогда сделать? Просто id проставить?

2024-12-19 10:38 UTC, Maxkanzas commented on src/main/java/core/clients/APIClient.java
> +                .get(ApiEndpoints.BOOKING.getPath())
Не понял, что ты ждешь от меня.

2024-12-19 10:39 UTC, Maxkanzas commented on src/main/java/core/clients/APIClient.java
> +    public Response getBookingId(){
Не понял

2024-12-19 10:39 UTC, Maxkanzas commented on src/main/java/core/clients/APIClient.java
> +                .get(ApiEndpoints.BOOKINGID.getPath())
не понял

2024-12-19 15:07 UTC, TsakunovR approved these changes

2024-12-19 15:50 UTC, merged